#spring:
#  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false

security:
  oauth2:
    client:
      client-id: 7f5ad3666146d81aa025
      client-secret: 5c76df8c163d91fc10a47cc4a79ac641fe2c9999
      scope: user
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
    resource:
      user-info-uri: https://api.github.com/user
